/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author vinaypawar
 */
public class SupplierWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SupplierWorkAreaJPanel
     */
    public SupplierWorkAreaJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        workArea = new javax.swing.JPanel();
        menuBar = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        btnPricePerformance = new javax.swing.JButton();
        btnAdjustPrice = new javax.swing.JButton();
        btnRunSimulation = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();

        jSplitPane1.setDividerLocation(90);
        jSplitPane1.setDividerSize(1);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setResizeWeight(0.1);
        jSplitPane1.setToolTipText("");

        workArea.setLayout(new java.awt.CardLayout());
        jSplitPane1.setBottomComponent(workArea);

        menuBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWelcome.setText("<WelcomeMsg>");
        menuBar.add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        btnPricePerformance.setText("Browse Price Performance");
        btnPricePerformance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPricePerformanceActionPerformed(evt);
            }
        });
        menuBar.add(btnPricePerformance, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        btnAdjustPrice.setText("Price Adjustment");
        btnAdjustPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdjustPriceActionPerformed(evt);
            }
        });
        menuBar.add(btnAdjustPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));

        btnRunSimulation.setText("Run Simulation");
        btnRunSimulation.setEnabled(false);
        btnRunSimulation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRunSimulationActionPerformed(evt);
            }
        });
        menuBar.add(btnRunSimulation, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, -1, -1));

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        menuBar.add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, -1, -1));

        jSplitPane1.setLeftComponent(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 881, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPricePerformanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPricePerformanceActionPerformed
        // TODO add your handling code here:

        PricePerformanceJPanel ppjp = new PricePerformanceJPanel(workArea, supplier);
        workArea.add(ppjp, "PricePerformancePanel");
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.show(workArea, "PricePerformancePanel");
    }//GEN-LAST:event_btnPricePerformanceActionPerformed

    private void btnAdjustPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdjustPriceActionPerformed
        // TODO add your handling code here:
        PriceAdjustmentJPanel atpjp = new PriceAdjustmentJPanel(workArea,supplier);
        workArea.add("AdjustTargetPriceJPanel",atpjp);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnAdjustPriceActionPerformed

    private void btnRunSimulationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRunSimulationActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnRunSimulationActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        mainWorkArea.remove(this);

        // Use CardLayout to switch back to login panel
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.first(mainWorkArea);

        // Optional: refresh the login panel if needed
        for (Component comp : mainWorkArea.getComponents()) {
            if (comp instanceof LoginMainJFrame) {
                ((LoginMainJFrame) comp).populateSupplierCombo();
            }
        }
    }//GEN-LAST:event_btnLogOutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdjustPrice;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnPricePerformance;
    private javax.swing.JButton btnRunSimulation;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel menuBar;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
